# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoRadioButton1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.labelHeader = QtWidgets.QLabel(Dialog)
        self.labelHeader.setGeometry(QtCore.QRect(120, 10, 121, 21))
        self.labelHeader.setObjectName("labelHeader")
        self.labelOutput = QtWidgets.QLabel(Dialog)
        self.labelOutput.setGeometry(QtCore.QRect(80, 230, 211, 31))
        self.labelOutput.setText("")
        self.labelOutput.setObjectName("labelOutput")
        self.radioButtonPython = QtWidgets.QRadioButton(Dialog)
        self.radioButtonPython.setGeometry(QtCore.QRect(60, 70, 82, 17))
        self.radioButtonPython.setObjectName("radioButtonPython")
        self.radioButtonCSharp = QtWidgets.QRadioButton(Dialog)
        self.radioButtonCSharp.setGeometry(QtCore.QRect(60, 100, 82, 17))
        self.radioButtonCSharp.setObjectName("radioButtonCSharp")
        self.radioButtonCpp = QtWidgets.QRadioButton(Dialog)
        self.radioButtonCpp.setGeometry(QtCore.QRect(60, 130, 82, 17))
        self.radioButtonCpp.setObjectName("radioButtonCpp")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelHeader.setText(_translate("Dialog", "Choose your Language"))
        self.radioButtonPython.setText(_translate("Dialog", "Python"))
        self.radioButtonCSharp.setText(_translate("Dialog", "C#"))
        self.radioButtonCpp.setText(_translate("Dialog", "C++"))
