# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 240)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 50, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 111, 16))
        self.label_2.setObjectName("label_2")
        self.labelResult = QtWidgets.QLabel(Dialog)
        self.labelResult.setGeometry(QtCore.QRect(150, 190, 101, 16))
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.lineEditA = QtWidgets.QLineEdit(Dialog)
        self.lineEditA.setGeometry(QtCore.QRect(180, 50, 113, 20))
        self.lineEditA.setObjectName("lineEditA")
        self.lineEditB = QtWidgets.QLineEdit(Dialog)
        self.lineEditB.setGeometry(QtCore.QRect(180, 80, 113, 20))
        self.lineEditB.setObjectName("lineEditB")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 110, 320, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonPlus = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonPlus.setObjectName("pushButtonPlus")
        self.horizontalLayout.addWidget(self.pushButtonPlus)
        self.pushButtonMinus = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonMinus.setObjectName("pushButtonMinus")
        self.horizontalLayout.addWidget(self.pushButtonMinus)
        self.pushButtonMultiply = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonMultiply.setObjectName("pushButtonMultiply")
        self.horizontalLayout.addWidget(self.pushButtonMultiply)
        self.pushButtonDivide = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonDivide.setObjectName("pushButtonDivide")
        self.horizontalLayout.addWidget(self.pushButtonDivide)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Enter First Number"))
        self.label_2.setText(_translate("Dialog", "Enter Second Number"))
        self.pushButtonPlus.setText(_translate("Dialog", "+"))
        self.pushButtonMinus.setText(_translate("Dialog", "-"))
        self.pushButtonMultiply.setText(_translate("Dialog", "*"))
        self.pushButtonDivide.setText(_translate("Dialog", "/"))
