# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoSpinner.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(498, 219)
        self._label = QtWidgets.QLabel(Dialog)
        self._label.setGeometry(QtCore.QRect(30, 70, 51, 16))
        self._label.setObjectName("_label")
        self._label_2 = QtWidgets.QLabel(Dialog)
        self._label_2.setGeometry(QtCore.QRect(20, 110, 61, 16))
        self._label_2.setObjectName("_label_2")
        self.lineEditBookPrice = QtWidgets.QLineEdit(Dialog)
        self.lineEditBookPrice.setGeometry(QtCore.QRect(90, 70, 113, 20))
        self.lineEditBookPrice.setObjectName("lineEditBookPrice")
        self.lineEditSugarPrice = QtWidgets.QLineEdit(Dialog)
        self.lineEditSugarPrice.setGeometry(QtCore.QRect(90, 110, 113, 20))
        self.lineEditSugarPrice.setObjectName("lineEditSugarPrice")
        self.lineEditBookAmount = QtWidgets.QLineEdit(Dialog)
        self.lineEditBookAmount.setEnabled(False)
        self.lineEditBookAmount.setGeometry(QtCore.QRect(300, 70, 113, 20))
        self.lineEditBookAmount.setObjectName("lineEditBookAmount")
        self.lineEditSugarAmount = QtWidgets.QLineEdit(Dialog)
        self.lineEditSugarAmount.setEnabled(False)
        self.lineEditSugarAmount.setGeometry(QtCore.QRect(300, 110, 113, 20))
        self.lineEditSugarAmount.setObjectName("lineEditSugarAmount")
        self.labelResult = QtWidgets.QLabel(Dialog)
        self.labelResult.setGeometry(QtCore.QRect(320, 190, 47, 13))
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.spinBoxBookAmount = QtWidgets.QSpinBox(Dialog)
        self.spinBoxBookAmount.setGeometry(QtCore.QRect(230, 70, 42, 22))
        self.spinBoxBookAmount.setObjectName("spinBoxBookAmount")
        self.doubleSpinBoxSugarAmount = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBoxSugarAmount.setGeometry(QtCore.QRect(220, 110, 62, 22))
        self.doubleSpinBoxSugarAmount.setObjectName("doubleSpinBoxSugarAmount")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self._label.setText(_translate("Dialog", "Book Price"))
        self._label_2.setText(_translate("Dialog", "Sugar Price"))
