# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoSliders.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 361)
        self._label = QtWidgets.QLabel(Dialog)
        self._label.setGeometry(QtCore.QRect(30, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self._label.setFont(font)
        self._label.setObjectName("_label")
        self._label_2 = QtWidgets.QLabel(Dialog)
        self._label_2.setGeometry(QtCore.QRect(30, 50, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self._label_2.setFont(font)
        self._label_2.setObjectName("_label_2")
        self._label_3 = QtWidgets.QLabel(Dialog)
        self._label_3.setGeometry(QtCore.QRect(30, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self._label_3.setFont(font)
        self._label_3.setObjectName("_label_3")
        self._label_4 = QtWidgets.QLabel(Dialog)
        self._label_4.setGeometry(QtCore.QRect(190, 100, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self._label_4.setFont(font)
        self._label_4.setObjectName("_label_4")
        self.lineEditResult = QtWidgets.QLineEdit(Dialog)
        self.lineEditResult.setGeometry(QtCore.QRect(90, 300, 231, 20))
        self.lineEditResult.setObjectName("lineEditResult")
        self.horizontalScrollBarSugar = QtWidgets.QScrollBar(Dialog)
        self.horizontalScrollBarSugar.setGeometry(QtCore.QRect(170, 20, 160, 16))
        self.horizontalScrollBarSugar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBarSugar.setObjectName("horizontalScrollBarSugar")
        self.horizontalSliderBloodPressure = QtWidgets.QSlider(Dialog)
        self.horizontalSliderBloodPressure.setGeometry(QtCore.QRect(170, 50, 160, 22))
        self.horizontalSliderBloodPressure.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderBloodPressure.setObjectName("horizontalSliderBloodPressure")
        self.verticalSliderCholesterolLevel = QtWidgets.QSlider(Dialog)
        self.verticalSliderCholesterolLevel.setGeometry(QtCore.QRect(340, 100, 22, 160))
        self.verticalSliderCholesterolLevel.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderCholesterolLevel.setObjectName("verticalSliderCholesterolLevel")
        self.verticalScrollBarPulseRate = QtWidgets.QScrollBar(Dialog)
        self.verticalScrollBarPulseRate.setGeometry(QtCore.QRect(130, 100, 16, 160))
        self.verticalScrollBarPulseRate.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarPulseRate.setObjectName("verticalScrollBarPulseRate")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self._label.setText(_translate("Dialog", "Sugar Level"))
        self._label_2.setText(_translate("Dialog", "Blood Pressure"))
        self._label_3.setText(_translate("Dialog", "Pulse Rate"))
        self._label_4.setText(_translate("Dialog", "Cholesterol Level"))
